FROM alpine:latest

# 切换国内源
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

ENV TZ Asia/Shanghai
# 修改时区
RUN apk update && apk --no-cache add bash tzdata \
    && cp -r -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 删除时区包
RUN apk del tzdata

# 在容器中创建一个目录
RUN mkdir -p /app/

# 复制最新的可执行文件到容器中
COPY  . /app

# 修改权限
RUN chmod +x /app/zbp

# 定位到容器的工作目录
WORKDIR /app/

ENTRYPOINT ["/app/zbp", "-c", "config.json"]
