FROM golang:1.20-alpine AS builder

RUN go env -w GO111MODULE=auto \
  && go env -w CGO_ENABLED=0 \
  && go env -w GOPROXY=https://goproxy.cn,direct

WORKDIR /build

COPY ./ .

RUN set -ex \
    && cd /build \
    && go build -ldflags "-s -w -extldflags '-static'" -o cqhttp

# Run
FROM alpine:latest

# 切换国内源
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

# 修改时区
RUN apk update && apk --no-cache add bash tzdata \
    && cp -r -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 删除时区包
RUN apk del tzdata

# 安装ffmpeg
RUN apk --no-cache add ffmpeg 

# 在容器中创建一个目录
RUN mkdir -p /app/

# 复制最新的可执行文件到容器中
COPY --from=builder /build/cqhttp /app/

# 修改权限
RUN chmod +x /app/cqhttp

ENV TZ="Asia/Shanghai"
ENV UID=99
ENV GID=100
ENV UMASK=002
# 定位到容器的工作目录
WORKDIR /app/
VOLUME [ "/app" ]
EXPOSE 6800 5700
ENTRYPOINT [ "/app/cqhttp" ]
